apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:xUf1TGXBuCQ=,iv:bi5Hw3paoeZAeeuqEMDDzRwhY1bOhMSiKSD0c9raL4Y=,tag:er6Lk22sxxqsPCI4HexnkA==,type:str]
    password: ENC[AES256_GCM,data:Y8jFien1PNAV6+fxHZ5PIQ==,iv:xU/UciClzocQSCUikP9euMvf/rzhnPaNig9lD6jKP1s=,tag:arNmaZkEZqNWwayq7OaaQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T11:12:10Z"
    mac: ENC[AES256_GCM,data:gPtPnLvwbdct0+E6lDSe8xJo1iE8aGkOhQ1NN4hM9luhHsKRbVu1NdyuS3mlAtsdfmqQgtMQ5XMOyJX3C4M6NCCM2+KeI41IJn6vtZxZR40sYHh46b928oNYT+WshHz68wauOzGzFITbpdB8usRDZnLg+fWfeYTQpqdnCiJyyRE=,iv:t17dcOgnHapFUQgD1v28PvNfQlq8EGvmZNf5HM+BAFw=,tag:C48H1sRckeLYDhz628FYyw==,type:str]
    pgp:
        - created_at: "2025-02-27T11:12:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DkZkfCXzxCx8SAQdATf+zmTh8PUWHoAzStIrgQLmYSjBuohM3b0xwwK8CulAw
            bItypwCeSGBC5wRdB4a3lB6+S1J35dr3QjxMb44hXyN6i+N0knben0KUayZbholn
            1GYBCQIQw0snYhKMAburgj+cQ9yZKrcXyVrnFI+qQO/Pr80LKIaXtKjo/A8n9dek
            prjqSF21jw30Fh+fwJuP932lxvxUnaDcbPwEIBylejj6PUXGKdRN3zX7pONmXp5Q
            /A5xNf3c2Ww=
            =VtxG
            -----END PGP MESSAGE-----
          fp: 16BE08973926A5AB4856879825DB47E67492ABA6
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
